### ISSUE TITLE
unzip missing

### ISSUE THREAD

**Issue by foreverpiano** [Vchitect/VBench#48]
Traceback (most recent call last):   File "/workspace/dhl/VBench/run_eval.py", line 166, in <module>     main()   File "/workspace/dhl/VBench/run_eval.py", line 152, in main     my_VBench.evaluate(   File "/workspace/dhl/VBench/vbench/__init__.py", line 144, in evaluate     submodules_dict = init_submodules(dimension_list, local=local, read_frame=read_fram e)   File "/workspace/dhl/VBench/vbench/utils.py", line 279, in init_submodules     subprocess.run(unzip_command, check=True)   File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/subprocess.py", line 503,  in run     with Popen(*popenargs, **kwargs) as process:   File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/subprocess.py", line 971,  in __init__     self._execute_child(args, executable, preexec_fn, close_fds,   File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/subprocess.py", line 1863 , in _execute_child     raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'unzip'

need to update requirenment.txt

**Comment by foreverpiano** [comment]
https://github.com/Vchitect/VBench/pull/49

**Comment by foreverpiano** [comment]
Another issue when testing dimension "color"
```
Traceback (most recent call last):
  File "/workspace/dhl/VBench/run_eval.py", line 166, in <module>
    main()
  File "/workspace/dhl/VBench/run_eval.py", line 152, in main
    my_VBench.evaluate(
  File "/workspace/dhl/VBench/vbench/__init__.py", line 157, in evaluate
    results = evaluate_func(cur_full_info_path, self.device, submodules_list, **kwargs)
  File "/workspace/dhl/VBench/vbench/object_class.py", line 54, in compute_object_class
    dense_caption_model.initialize_model_det(**submodules_dict)
  File "/workspace/dhl/VBench/vbench/third_party/grit_model.py", line 17, in initialize_model_det
    self.demo = init_demo(self.device, model_weight = model_weight, task="ObjectDet")
  File "/workspace/dhl/VBench/vbench/third_party/grit_src/image_dense_captions.py", line 109, in init_demo
    demo = VisualizationDemo(cfg)
  File "/workspace/dhl/VBench/vbench/third_party/grit_src/grit/predictor.py", line 102, in __init__
    self.predictor = SingleDefaultPredictor(cfg)
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 155, in load
    checkpoint = self._load_file(path)
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 99, in _load_file
    loaded = self._torch_load(filename)
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 114, in _torch_load
    return super()._load_file(f)
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 252, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
/workspace/rlsu/miniconda3/envs/vbench/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

```
@ziqihuangg  @NattapolChan

**Comment by NattapolChan** [comment]
unzip should be command-line tool not the one from Pypi package. 

`sudo apt-get install unzip`

**Comment by ziqihuangg** [comment]
Hi, we're closing the issue since there is no follow-up question, but feel free to re-open it if you have any further questions!
